apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
  labels:
    app: calc
  namespace: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
       - name: calc
         image: wkandek/calc:1.2
         imagePullPolicy: Always
         ports:
         - containerPort: 8080
         resources:
           limits:
             cpu: "0.1"
           requests:
             cpu: "0.1"
         readinessProbe:
           httpGet:
             scheme: HTTP
             path: /metrics
             port: 8080
           initialDelaySeconds: 10
           periodSeconds: 5
